# Generated by Django 4.1.1 on 2022-10-07 16:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addmoney_info',
            new_name='Addexpense_info',
        ),
        migrations.RenameField(
            model_name='addexpense_info',
            old_name='add_money',
            new_name='add_expense',
        ),
    ]
